#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.sol2,v 1.1 2006/12/31 09:04:24 lzl Exp $
#

include ../Makedefs.com

CFLAGS = -DSTREAMS -I../include $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
